version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ims_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ims_database
      DB_USERNAME: ims_user
      DB_PASSWORD: password

  nginx:
    image: nginx:alpine
    container_name: ims_nginx
    restart: unless-stopped
    ports:
      - "8880:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: ims_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ims_database
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: ims_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ims_phpmyadmin
    restart: unless-stopped
    ports:
      - "8085:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
