{{-- resources/views/reports/pdf.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->formatted_type }}</title>
    <style>
        body { font-family: sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .metadata { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f8f9fa; }
        .footer { margin-top: 20px; font-size: 0.8em; }
    </style>
</head>
<body>
    <div class="header">
        <h2>{{ config('app.name') }}</h2>
        <h3>{{ $report->formatted_type }}</h3>
        <p>Report Number: {{ $report->report_number }}</p>
    </div>

    <div class="metadata">
        <p><strong>Branch:</strong> {{ $report->branch?->name ?? 'All Branches' }}</p>
        <p><strong>Date Range:</strong> {{ $report->date_range }}</p>
        <p><strong>Generated By:</strong> {{ $report->generatedBy->username }}</p>
        <p><strong>Generated At:</strong> {{ $generated_at }}</p>
    </div>

    <table>
        <thead>
            <tr>
                @forelse($report->data[0] ?? [] as $key => $value)
                    <th>{{ ucwords(str_replace('_', ' ', $key)) }}</th>
                @empty
                    <th>No Data Available</th>
                @endforelse
            </tr>
        </thead>
        <tbody>
            @forelse($report->data as $row)
                <tr>
                    @foreach($row as $value)
                        <td>
                            @if(is_array($value))
                                {{ json_encode($value) }}
                            @elseif(is_null($value))
                                -
                            @else
                                {{ $value }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($report->data[0] ?? []) ?: 1 }}">No data available</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Generated from {{ config('app.name') }} on {{ $generated_at }}</p>
    </div>
</body>
</html>
