@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div class="d-flex align-items-center">
            <a href="{{ route('reports.index') }}" class="btn btn-outline-primary btn-icon-split me-3">
                <span class="icon"><i class="bi bi-arrow-left"></i></span>
                <span class="text">Back</span>
            </a>
            <h1 class="h3 mb-0 text-gray-800">Report Details</h1>
        </div>
        <div class="btn-group">
            <a href="{{ route('reports.download.pdf', $report) }}" 
               class="btn btn-primary btn-icon-split">
                <span class="icon"><i class="bi bi-file-pdf"></i></span>
                <span class="text">Download PDF</span>
            </a>
            
            <a href="{{ route('reports.download.excel', $report) }}" 
               class="btn btn-success btn-icon-split ms-2">
                <span class="icon"><i class="bi bi-file-excel"></i></span>
                <span class="text">Download Excel</span>
            </a>
        </div>
    </div>

    <div class="card shadow mb-4">
        <div class="card-header py-3 d-flex justify-content-between align-items-center bg-gradient-primary">
            <h6 class="m-0 font-weight-bold text-white">{{ $report->formatted_type }}</h6>
            <span class="badge bg-white text-primary">{{ $report->report_number }}</span>
        </div>
        <div class="card-body">
            <div class="row mb-4">
                <div class="col-md-6">
                    <div class="info-group">
                        <p><i class="bi bi-building me-2"></i><strong>Branch:</strong> {{ $report->branch?->name ?? 'All Branches' }}</p>
                        <p><i class="bi bi-calendar-range me-2"></i><strong>Date Range:</strong> {{ $report->date_range }}</p>
                        <p><i class="bi bi-list-ol me-2"></i><strong>Total Records:</strong> {{ number_format($report->total_records) }}</p>
                    </div>
                </div>
                <div class="col-md-6 text-md-end">
                    <div class="info-group">
                        <p><i class="bi bi-person me-2"></i><strong>Generated By:</strong> {{ $report->generatedBy->username }}</p>
                        <p><i class="bi bi-clock me-2"></i><strong>Generated At:</strong> {{ $report->created_at->format('M d, Y H:i:s') }}</p>
                        @if($report->total_amount > 0)
                            <p><i class="bi bi-currency-dollar me-2"></i><strong>Total Amount:</strong> {{ number_format($report->total_amount, 2) }}</p>
                        @endif
                    </div>
                </div>
            </div>

            <div class="table-responsive">
                <table class="table table-bordered table-hover" id="reportDataTable">
                    <thead>
                        <tr>
                            @foreach($report->data[0] ?? [] as $key => $value)
                                <th>{{ ucwords(str_replace('_', ' ', $key)) }}</th>
                            @endforeach
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($report->data as $row)
                            <tr>
                                @foreach($row as $key => $value)
                                    <td>
                                        @if(is_array($value))
                                            {{ json_encode($value) }}
                                        @elseif(is_numeric($value) && (str_contains($key, 'amount') || str_contains($key, 'price')))
                                            {{ number_format($value, 2) }}
                                        @elseif(is_numeric($value) && str_contains($key, 'quantity'))
                                            {{ number_format($value) }}
                                        @else
                                            {{ $value }}
                                        @endif
                                    </td>
                                @endforeach
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
$(document).ready(function() {
    $('#reportDataTable').DataTable({
        pageLength: 25,
        ordering: true,
        responsive: true,
        dom: '<"d-flex justify-content-between align-items-center mb-3"lf>rt<"d-flex justify-content-between align-items-center"ip>',
        language: {
            search: "Search records:"
        }
    });
});
</script>
@endpush

@push('styles')
<style>
.btn-icon-split {
    padding: 0;
}
.btn-icon-split .icon {
    padding: 0.375rem 0.75rem;
    background: rgba(0,0,0,0.15);
    display: inline-block;
}
.btn-icon-split .text {
    padding: 0.375rem 0.75rem;
    display: inline-block;
}
.info-group p {
    margin-bottom: 0.5rem;
}
.bg-gradient-primary {
    background: linear-gradient(45deg, #4e73df, #224abe);
}
#reportDataTable thead th {
    background-color: #f8f9fc;
    border-bottom: 2px solid #e3e6f0;
}
#reportDataTable tbody tr:hover {
    background-color: #f8f9fc;
}
</style>
@endpush
